corkandsip/corkandsip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

corkandsip/main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # Guests
    path('guests/', views.guests_index, name='index'),
    path('guests/<int:guest_id>/', views.guests_detail, name='detail'),
    path('guests/create/', views.GuestCreate.as_view(), name='guests_create'),
    path('guests/<int:pk>/update/',
         views.GuestUpdate.as_view(), name='guests_update'),
    path('guests/<int:pk>/delete/',
         views.GuestDelete.as_view(), name='guests_delete'),
    # Tastings
    path('guests/<int:guest_id>/add_tasting',
         views.add_tasting, name='add_tasting'),
    # Wines
    path('wines/', views.WineList.as_view(), name='wines_index'),
    path('wines/<int:pk>/', views.WineDetail.as_view(), name='wines_detail'),
    path('wines/create', views.WineCreate.as_view(), name='wines_create'),
    path('wines/<int:pk>/update/', views.WineUpdate.as_view(), name='wines_update'),
    path('wines/<int:pk>/delete/', views.WineDelete.as_view(), name='wines_delete'),
    # Cellar
    path('guests/<int:guest_id>/add_to_cellar/<int:wine_id>/',
         views.add_to_cellar, name="add_to_cellar"),
    path('guests/<int:guest_id>/remove_from_cellar/<int:wine_id>/',
         views.remove_from_cellar, name="remove_from_cellar"),
    # Account Sign-Up
    path('accounts/signup/', views.signup, name='signup'),
]

corkandsip/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

TASTINGS = (
    ('M', '11:30 AM'),
    ('A', '2:00 PM'),
    ('N', '6:00 PM'),
)


class Wine(models.Model):
    producer = models.CharField(max_length=50)
    vintage = models.CharField(max_length=50)
    region = models.CharField(max_length=50)

    def __str__(self):
        return self.producer

    def get_absolute_url(self):
        return reverse('wines_detail', kwargs={'pk': self.id})


class Guest(models.Model):
    username = models.CharField(max_length=30)
    user_Email = models.EmailField(max_length=70, blank=True, unique=True)
    user_Phone = models.CharField(max_length=10)
    wine = models.ManyToManyField(Wine)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('detail', kwargs={'guest_id': self.id})

    def tasting_for_today(self):
        return self.tasting_set.filter(date=date.today()).count() >= len(TASTINGS)


class Tasting(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateField('Tasting Date')
    time = models.CharField(
        max_length=1,
        choices=TASTINGS,
        default=TASTINGS[0][0]
    )

    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_tasting_display()} on {self.date}"

    class Meta:
        ordering = ['-date']


class Collection(models.Model):
    producer = models.CharField(max_length=50)

    def __str__(self):
        return self.producer

corkandsip/main_app/forms.py
from django.forms import ModelForm
from .models import Tasting

class TastingForm(ModelForm):
  class Meta:
    model = Tasting
    fields = ['date', 'time']

corkandsip/main_app/views.py
from django.shortcuts import render, redirect
# CRUD Views
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
# User Creation & Sign Up
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Guest, Wine
from .forms import TastingForm

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def guests_index(request):
    guests = Guest.objects.filter(user=request.user)
    return render(request, 'guests/index.html',
                  {'guests': guests})


@login_required
def guests_detail(request, guest_id):
    guest = Guest.objects.get(id=guest_id)
    id_list = guest.wine.all().values_list('id')
    wines_guest_doesnt_have = Wine.objects.exclude(id__in=id_list)
    tasting_form = TastingForm()
    return render(request, 'guests/detail.html', {
        'guest': guest,
        'tasting_form': tasting_form,
        'wines': wines_guest_doesnt_have
    })


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class GuestCreate(LoginRequiredMixin, CreateView):
    model = Guest
    fields = ['username', 'user_Email', 'user_Phone']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class GuestUpdate(LoginRequiredMixin, UpdateView):
    model = Guest
    fields = ['user_Email', 'user_Phone']


class GuestDelete(LoginRequiredMixin, DeleteView):
    model = Guest
    success_url = '/guests'


@login_required
def add_tasting(request, guest_id):
    form = TastingForm(request.POST)
    if form.is_valid():
        new_tasting = form.save(commit=False)
        new_tasting.guest_id = guest_id
        new_tasting.save()
    return redirect('detail', guest_id=guest_id)


class WineList(LoginRequiredMixin, ListView):
    model = Wine


class WineDetail(LoginRequiredMixin, DetailView):
    model = Wine


class WineCreate(LoginRequiredMixin, CreateView):
    model = Wine
    fields = '__all__'


class WineUpdate(LoginRequiredMixin, UpdateView):
    model = Wine
    fields = '__all__'


class WineDelete(LoginRequiredMixin, DeleteView):
    model = Wine
    success_url = '/wines'


@login_required
def add_to_cellar(request, guest_id, wine_id):
    Guest.objects.get(id=guest_id).wine.add(wine_id)
    return redirect('detail', guest_id=guest_id)


@login_required
def remove_from_cellar(request, guest_id, wine_id):
    Guest.objects.get(id=guest_id).wine.remove(wine_id)
    return redirect('detail', guest_id=guest_id)

corkandsip/main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>ABOUT US</h1>
<hr />
<p> Whether you're a seasoned sommelier or just beginning your wine journey, our app is your gateway to a world of vineyards, wineries, and tastings that will tantalize your taste buds and deepen your appreciation for the vine. Embark on an adventure filled with swirling glasses, captivating stories, and the delight of discovering new winemakers. From elegant reds to crisp whites, sparkling bubbles to rare vintages, we offer a diverse range of options to cater to every palate. Our mission is to make wine tasting accessible, enjoyable, and enriching for everyone, fostering a community that shares a genuine love for wine. So, let us be your trusted companion in unlocking the secrets of wine, as we invite you to savor every Cork & Sip while create lasting memories through us.
</p>
<h2>MEET THE OWNERS</h2>
<hr />
<br>
<div class="row">
  <div class="col s4 section">
    <img style="padding: 20px;" class="circle responsive-img" src="https://i.ibb.co/6v5kcZ5/Website-Photo.png"  alt="tonysprofilepic">
  </div>
  <div class="col s4 section">
    <img style="padding: 10px; margin-top: 10px;" class="circle responsive-img" src="https://i.ibb.co/Z6WcXGm/Slack-Photo.png" alt="jamesprofilepic">
  </div>
  <div class="col s4 section">
    <img style="padding: 10px; margin-top: 10px;" class="circle responsive-img" src="https://i.ibb.co/Ws6vs01/IMG-1106.jpg" alt="micolesprofilepic">
  </div>
</div>
<div class="row">
  <div class="col s4 section">
    <h3 style="text-align: center;">Tony</h3>
    <br>
    <br>
    <p>Born and raised in Atlanta, GA. I have 11 years of experience in the service and food industry. My extensive knowledge of the service and food industry and customer service played a part in the inspiration for this app.<p>
  </div>
  <div class="col s4 section">
    <h3 style="text-align: center;">James</h3>
    <br>
    <br>
    <p>Born and raised in San Jose, CA and now I currently reside in Tulsa, OK. I have an experience of being a bartender/sommelier at Lowood, one of Tulsa's top restaurants. I gained my intro level sommelier certification through the Court of Master Sommeliers. My passion for the industry was part of the inspiration for the app.<p>
  </div>
  <div class="col s4 section">
    <h3 style="text-align: center;">Micole</h3>
    <br>
    <br>
    <p>Born and raised in Memphis,TN and now I currently reside in Dallas,TX. I have background within the food and club industry. As a former server and also a wine enthusiast I was inspired to play a role in creating this app.<p>
  </div>
</div>

{% endblock %}

corkandsip/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cork & Sip</title>
  <!--GOOGLE FONTS BELOW-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Just+Another+Hand&family=Parisienne&family=Rochester&display=swap" rel="stylesheet">
  <!--GOOGLE FONTS ABOVE-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
  
<body style="font-family: 'Courier New', Courier, monospace; background-image: url('https://images.unsplash.com/photo-1601662528567-526cd06f6582?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=415&q=80');" >
  <ul id="dropdown1" class="dropdown-content">
    <li><a class = "black-text" href="{% url 'guests_create' %}">Add a Guest</a></li>
    <li class="divider"></li>
    <li><a class = "black-text" href="{% url 'index' %}">View All Guests</a></li>


  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><a class = "black-text" href="{% url 'wines_create' %}">Add a Wine</a></li>
    <li class="divider"></li>
    <li><a class = "black-text" href="{% url 'wines_index' %}">View All Wines</a></li>
  </ul>
  <nav>
    <div class="nav-wrapper pink darken-4">
      <ul>
        <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp; Cork & Sip</a></li>
      </ul>
      <ul class="right">
        <li><a href="{% url 'about' %}">About</a></li>
        {% if user.is_authenticated %}
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1" >Guests<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2" >Wines<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          </ul>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="banner">
  </div>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer pink darken-4">
    <div class="right">All Rights Reserved, &copy; 2023 Cork & Sip &nbsp;</div>
  </footer>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
  
    const selectEl = document.getElementById('id_time');
    M.FormSelect.init(selectEl);
  });
  document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('.dropdown-trigger');
    var instances = M.Dropdown.init(elems); 
  });
  </script>
</body>
</html>

corkandsip/main_app/templates/guests/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Guest Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ guest.username }}</span>
        <p>Email: {{ guest.user_Email }}</p>
        <p>Phone Number: {{ guest.user_Phone }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'guests_update' guest.id %}">Edit</a>
        <a href="{% url 'guests_delete' guest.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_tasting' guest.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ tasting_form.as_p }}
      {{ tasting_form.time.as_p }}
      <input type="submit" class="btn" value="Add Tasting">
    </form>
    <br>
    <table class="striped">
      <thead>
        <tr>
          <th id = "date-tasting-header">Date  </th>
          <th id = "date-tasting-header">Tasting</th>
        </tr>
      </thead>
      <tbody>
        {% for tasting in guest.tasting_set.all %}
          <tr>
            <td>{{tasting.date}}</td>
            <td>{{tasting.get_time_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Wine Cellar Section -->
<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ guest.username }}'s Cellar</h3>
    {% if guest.wine.count %} {% for wine in guest.wine.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ wine.producer }}
        </span>
        <p>Vintage: {{ wine.vintage }} </p>
        <p>Region: {{ wine.region }}</p>
      </div>
      <div class="card-action">
        <form action="{% url 'remove_from_cellar' guest.id wine.id%}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %} 
    {% else %}
    <h5>No Wines Added</h5>
    {% endif %}
  </div>
</div>
<div class="col s6">
  <h3>Available Wines</h3>
  {% if wines.count %}
    {% for wine in wines.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ wine.producer }}
          </span>
          <p>Vintage: {{ wine.vintage }} </p>
          <p>Region: {{ wine.region }}</p>
        </div>
        <div class="card-action">
          <form action="{% url 'add_to_cellar' guest.id wine.id%}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{guest.username}} has collected all available wines!</h5>
  {% endif %}
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_time');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

corkandsip/main_app/templates/guests/index.html
{% extends 'base.html' %} {% block content %}

<h1 class = "card-content valign center">Guests on Account</h1>

{% for guest in guests %}
<div class="card">
  <a href="{% url 'detail' guest.id %}">
    <div style="color: black;" class="card-content">
      <span class="card-title">{{ guest.username }}</span>
      <p>Email: {{ guest.user_Email }}</p>
      <p>Phone Number: {{ guest.user_Phone }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

corkandsip/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<p style="text-align: center;">Maybe you're a sommelier, maybe you're like "sommel-what? I don't even know what that is."  We would like to introduce you to Cork & Sip. The "Cork & Sip" app is where wine enthusiasts can explore the world of wine by booking tasting events across Napa Valley, adding their favorite wines to their own personal "cellar" as they go, and adding wines they would like to see in our collection!</p>
  <hr>
  <br>
      <div class="row">
        <div class="col s4 section">
          <h5 style="text-align: center;">Visit our vineyard!</h5>
        </div>
        <div class="col s4 section">
          <h5 style="text-align: center;">Join us for a tasting!</h5>
        </div>
        <div class="col s4 section">
          <h5 style="text-align: center;">Start a collection!</h5>
        </div>
        <div class="row">
          <div class="col s4 section">
            <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1607843449148-60c1da77a0c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80" alt="Vineyard">
          </div>
          <div class="col s4 section">
            <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2luZXJ5fGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60" alt="Tasting">
          </div>
          <div class="col s4 section">
            <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1611575189074-9dfbbceb258a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2luZSUyMGNlbGxhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60" alt="Cellar">
          </div>
      </div>
  <nav style="background-color:#880e4f;">
    <div style="text-align: center; color:white;"> Contact us today at corkandsip@gmail.com or give us a call at 555-123-4567!</div>
  </nav>
<hr>
<br>
<div class="row">
  <div class="col s4 section">
    <h5 style="text-align: center;">Visit our vineyard!</h5>
  </div>
  <div class="col s4 section">
    <h5 style="text-align: center;">Join us for a tasting!</h5>
  </div>
  <div class="col s4 section">
    <h5 style="text-align: center;">Start a collection!</h5>
</div>
<div class="row">
  <div class="col s4 section">
    <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1607843449148-60c1da77a0c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80" alt="Vineyard">
  </div>
  <div class="col s4 section">
    <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2luZXJ5fGVufDB8fDB8fHww&auto=format&fit=crop&w=400&q=60" alt="Tasting">
  </div>
  <div class="col s4 section">
    <img id = "home-img" class="circle responsive-img" src="https://images.unsplash.com/photo-1611575189074-9dfbbceb258a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2luZSUyMGNlbGxhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=400&q=60" alt="Cellar">
  </div>
</div>
<nav style="background-color:#880e4f;">
  <div style="text-align: center; color:white;"> Contact us today at corkandsip@gmail.com or give us a call at 555-123-4567!</div>
</nav>

{% endblock %}

corkandsip/main_app/templates/main_app/guest_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Guest</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.user_name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' guest.id %}">Cancel</a>
  </form>
{% endblock %}

corkandsip/main_app/templates/main_app/guest_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{ object.user_name }}</span></h1>
  {% else %}
    <h1 class = "card-content valign center">Add Guest</h1>
    <p class = "card-content valign center">Want to bring friends and family? Make sure you add them to your reservation!</p>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <br>
    <input type="submit" value="Submit!" class="btn">
  </form>
  <br>
{% endblock %}

corkandsip/main_app/templates/main_app/wine_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete A Wine</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' wine.id %}">Cancel</a>
  </form>
{% endblock %}

corkandsip/main_app/templates/main_app/wine_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Wine Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ wine.producer }}</span>
        <p>Region: {{ wine.region }}</p>
          <p>Vintage: {{ wine.vintage }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'wines_update' wine.id %}">Edit</a>
        <a href="{% url 'wines_delete' wine.id %}">Delete</a>
      </div>
    </div>
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11948175.05338434!2d-8.863193367490476!3d45.465632896552!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1687317195557!5m2!1sen!2sus" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>
  <div class="col s2 section" ></div>
  <div class="col s4 section" >
    <img class= "responsive-img" style="width: 350px; border-radius: 10px;" src="https://images.unsplash.com/photo-1553703189-2f8ce8a11bcc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fHdpbmUlMjBib3R0bGV8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60" alt="Wine">
  </div>
</div>
  {% endblock %}

corkandsip/main_app/templates/main_app/wine_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{ object.name}}</span></h1>
{% else %}
<h1 class = "card-content valign center">Add Wine</h1>
<p class = "card-content valign center">Add one of your favorite wines that you want to see in our collection!</p>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br>
  <input type="submit" value = "Submit!" class="btn">
</form>
<br>

{% endblock %}

corkandsip/main_app/templates/main_app/wine_list.html
{% extends 'base.html' %}
{% block content %}

<h1 class="card-content valign center">Our Collection of Wines</h1>

<div class="row">
{% for wine in wine_list %}
  <a href="{% url 'wines_detail' wine.id %}">
    <div class="col s4">
      <div class="card">
          <div class="card-content">
              <span style="color: black;" class="card-title">{{ wine.producer }}</span>
              <p style="color: black;" >Vintage: {{ wine.vintage }}</p>
              <p style="color: black;" >Region: {{ wine.region }}</p>
          </div>
      </div>
    </div>
  </a>
{% endfor %}
</div>
{% endblock %}